In [ ]:
import numpy as np


In [ ]:
import seaborn as sns

In [ ]:
import matplotlib.pyplot as plt


In [ ]:
data=np.load("/content/drive/My Drive/Colab Notebooks/whole/data.npy", mmap_mode=None, allow_pickle=True, fix_imports=True, encoding='ASCII')

In [ ]:
data.shape

(1280, 34160)

In [ ]:
labels=np.load("/content/drive/My Drive/Colab Notebooks/whole/labels.npy", mmap_mode=None, allow_pickle=True, fix_imports=True, encoding='ASCII')

In [ ]:
labels.shape

(1280, 4)

# valence


In [ ]:
y1=labels[:,0]
y1

array([7.71, 8.1 , 8.58, ..., 3.05, 3.99, 7.15])

In [ ]:
y1=(y1>5).astype(int)

In [ ]:
y1

array([1, 1, 1, ..., 0, 0, 1])

In [ ]:
X=data

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
scalar=StandardScaler()

In [ ]:
X=scalar.fit_transform(X)

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train,X_test,y1_train,y1_test=train_test_split(X,y1,test_size=20,random_state=21)

In [ ]:
from sklearn import svm

In [ ]:
clf1 = svm.SVC()
clf1.fit(X_train, y1_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
clf1.score(X_test,y3_test)

0.6

# arousal


In [ ]:
y2=labels[:,1]
y2

array([7.6 , 7.31, 7.54, ..., 7.01, 7.17, 4.03])

In [ ]:
y2=(y2>5).astype(int)

In [ ]:
y2

array([1, 1, 1, ..., 1, 1, 0])

In [ ]:
X=data

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
scalar=StandardScaler()

In [ ]:
X=scalar.fit_transform(X)

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train,X_test,y2_train,y2_test=train_test_split(X,y2,test_size=20,random_state=21)

In [ ]:
from sklearn import svm

In [ ]:
clf2 = svm.SVC()
clf2.fit(X_train, y2_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
clf2.score(X_test,y2_test)

0.65

# Liking


In [ ]:
y4=labels[:,3]
y4

array([7.83, 8.47, 7.08, ..., 1.1 , 1.  , 1.88])

In [ ]:
y4=(y4>5).astype(int)

In [ ]:
y4

array([1, 1, 1, ..., 0, 0, 0])

In [ ]:
X=data

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
scalar=StandardScaler()

In [ ]:
X=scalar.fit_transform(X)

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train,X_test,y4_train,y4_test=train_test_split(X,y4,test_size=20,random_state=21)

In [ ]:
from sklearn import svm

In [ ]:
clf4 = svm.SVC()
clf4.fit(X_train, y4_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
clf4.score(X_test,y4_test)

0.65

# dominance


In [ ]:
y3=labels[:,2]
y3

array([6.9 , 7.28, 9.  , ..., 5.1 , 4.85, 9.  ])

In [ ]:
y3=(y3>5).astype(int)

In [ ]:
y3

array([1, 1, 1, ..., 1, 0, 1])

In [ ]:
X=data

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
scalar=StandardScaler()

In [ ]:
X=scalar.fit_transform(X)

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train,X_test,y3_train,y3_test=train_test_split(X,y3,test_size=20,random_state=21)

In [ ]:
from sklearn import svm

In [ ]:
clf3 = svm.SVC()
clf3.fit(X_train, y3_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
clf3.score(X_test,y3_test)

0.6